apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogue
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      containers:
      - name: productcatalogue
        image: ossamaferjani/java-k8s:productcatalogue-latest
        ports:
        - containerPort: 8020
        livelinessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  labels:
    app: productcatalogue
spec:
  type: NodePort
  selector:
    app: productcatalogue
  ports:
  protocol: TCP
  port: 8020
  name: http

