apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
spec:
  spec:
  selector:
    matchLabels:
      app: stockmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
      - name: stockmanager
        image: ossamaferjani/java-k8s:stock-latest
        ports:
        - containerPort: 8030
        livenessProbe:
          httpGet:
            path: /health
            port: 8030
          initialDelaySeconds: 30
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  type: NodePort
  selector:
    app: stockmanager
  ports:
    - protocol: TCP
      port: 8030
      targetPort: 8030  # Define if different from the port value
      name: http
      nodePort: 31000   # Specify a specific nodePort if needed


---